### PR TITLE
Emma's changes

### PR DESCRIPTION
**Pull request by emmadcle**

### CODE REVIEW

**Comment by emmadcle** [comment]
@msalinero please give me access :)

**Comment by msalinero** [comment]
Sure! Can´t @psreyes and @daviddkovacs do it also?

**Comment by emmadcle** [comment]
Yeah it's already fixed, pablo gave me access, thanks
________________________________
Van: msalinero ***@***.***>
Verzonden: vrijdag 25 oktober 2024 12:55
Aan: SentiFLEXinel/EBD-GPR-CNC ***@***.***>
CC: Emma De Clerck ***@***.***>; State change ***@***.***>
Onderwerp: Re: [SentiFLEXinel/EBD-GPR-CNC] Emma's changes (PR #2)


Sure! Can´t @psreyes<https://github.com/psreyes> and @daviddkovacs<https://github.com/daviddkovacs> do it also?

**Comment by msalinero** [comment]
No problem!

**Pull request merged**
